# Generated by Django 4.1.7 on 2023-03-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='name',
            new_name='descripton',
        ),
    ]
