# Generated by Django 4.1.7 on 2023-03-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_rename_name_todolist_descripton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='descripton',
            new_name='description',
        ),
    ]
