# Generated by Django 4.1.7 on 2023-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
