# Generated by Django 4.1.7 on 2023-03-25 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
