# Generated by Django 4.1.7 on 2023-03-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=70000),
        ),
    ]
