# Generated by Django 4.1.7 on 2023-04-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_alter_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
