# Generated by Django 4.1.7 on 2023-04-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('note', '0009_note_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ManyToManyField(related_name='image', to='image.image'),
        ),
    ]
