# Generated by Django 4.1.7 on 2023-04-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('note', '0010_remove_note_image_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ManyToManyField(null=True, related_name='image', to='image.image'),
        ),
    ]
