# Generated by Django 4.1.7 on 2023-04-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('note', '0011_alter_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='image', to='image.image'),
        ),
    ]
