# Generated by Django 4.1.7 on 2023-03-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('deadline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_deadline', to='subject.subject'),
        ),
    ]
